#!/bin/bash
# ============================================================================
# Builds the web userscript (claude-rtl.user.js) from the SHARED payload.
#
# The RTL detection logic in ../shared/rtl-payload.js is the single source of
# truth. The desktop patcher prepends it into Claude Desktop's app.asar; this
# script wraps the exact same code in a Tampermonkey/Violentmonkey userscript
# header so it runs on claude.ai in a browser. One logic, two delivery pipes.
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PAYLOAD="$SCRIPT_DIR/../shared/rtl-payload.js"
OUT="$SCRIPT_DIR/claude-rtl.user.js"
VERSION="${1:-1.0.0}"

[ -f "$PAYLOAD" ] || { echo "ERROR: shared payload not found at $PAYLOAD"; exit 1; }

{
cat <<HEADER
// ==UserScript==
// @name         Claude RTL (Hebrew / Arabic)
// @namespace    https://github.com/Zeev-L/claude-hebrew-support
// @version      ${VERSION}
// @description  Auto right-to-left for Hebrew/Arabic on claude.ai — keeps code, LaTeX and English LTR. Works while responses stream.
// @author       Zeev-L (RTL logic by @shraga100, macOS port by @soguy)
// @match        https://claude.ai/*
// @run-at       document-idle
// @grant        GM_addStyle
// ==/UserScript==
//
// NOTE: @grant is intentionally set (GM_addStyle) rather than 'none'. With
// '@grant none' Tampermonkey injects the script into the page context, which
// claude.ai's Content-Security-Policy blocks — so the script never runs. Any
// non-none @grant makes Tampermonkey run it in its isolated sandbox (still with
// full DOM access), which is not subject to the page CSP. The payload only does
// DOM work, so the sandbox context is all it needs.

// NOTE: This file is GENERATED by build-web.sh from ../shared/rtl-payload.js.
// Edit the shared payload, not this file, then re-run build-web.sh.

HEADER
cat "$PAYLOAD"
} > "$OUT"

echo "Built $OUT (v$VERSION)"
